---
apiVersion: v1
kind: Service
metadata:
  name: test-app-warm-nodeport
  labels:
    app: test-app-warm
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
      protocol: TCP
      name: http
  selector:
    app: test-app-warm
---
apiVersion: v1
kind: Service
metadata:
  name: serverless-activator-nodeport
  labels:
    app: serverless-activator
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8081
      nodePort: 30081
      protocol: TCP
      name: http
  selector:
    app: serverless-activator
