/**
 * ClarkNet Trace-Driven Replay (fib34 fixed) — k6 Load Test
 *
 * Generated by scripts/generate_trace_replay.py
 * Uses ramping-arrival-rate executor with 30-second stages derived from
 * the ClarkNet HTTP trace (Section 3.2.4 of thesis methodology).
 *
 * Usage:
 *   k6 run infrastructure/load-tests/clarknet_replay_fib34.js \
 *     -e TARGET_URL=http://localhost:18082 \
 *     -e SCENARIO=s4-hybrid-predictive
 */

import http from 'k6/http';
import { check } from 'k6';
import { Rate, Trend, Counter } from 'k6/metrics';

const errorRate = new Rate('errors');
const latencyTrend = new Trend('latency_ms');
const requestCounter = new Counter('total_requests');
const sloViolations = new Counter('slo_violations');

const SLO_THRESHOLD_MS = 200;

// Load stages from generated JSON
const stages = JSON.parse(open('../../data/trace-replay/clarknet_k6_stages.json'));

export const options = {
    scenarios: {
        clarknet_replay: {
            executor: 'ramping-arrival-rate',
            startRate: stages[0].target,
            timeUnit: '1s',
            preAllocatedVUs: 200,
            maxVUs: 400,
            stages: stages,
        },
    },
    thresholds: {
        'http_req_duration': ['p(95)<2000', 'p(99)<5000'],
        'http_req_failed': ['rate<0.10'],
    },
};

const BASE_URL = __ENV.TARGET_URL || __ENV.BASE_URL || 'http://localhost:18082';
const ENDPOINT = '/fib?n=34';

export function setup() {
    console.log('\n🔬 ClarkNet Trace-Driven Replay');
    console.log('================================');
    console.log(`Stages: ${stages.length}`);
    console.log(`Duration: ${stages.length * 30}s (${(stages.length * 30 / 60).toFixed(1)} min)`);
    const rps_values = stages.map(s => s.target);
    console.log(`RPS range: [${Math.min(...rps_values)}, ${Math.max(...rps_values)}]`);
    console.log(`Target: ${BASE_URL}${ENDPOINT}`);
    console.log('');

    const warmup = http.get(`${BASE_URL}${ENDPOINT}`, {
        headers: { 'Host': 'test-app.default.127.0.0.1.sslip.io' },
    });
    if (warmup.status !== 200) {
        console.log(`⚠️ Warning: Warmup request returned ${warmup.status}`);
    }

    return { startTime: Date.now() };
}

export default function () {
    const res = http.get(`${BASE_URL}${ENDPOINT}`, {
        headers: {
            'Host': 'test-app.default.127.0.0.1.sslip.io',
        },
    });

    const duration = res.timings.duration;
    latencyTrend.add(duration);
    requestCounter.add(1);

    if (duration > SLO_THRESHOLD_MS) {
        sloViolations.add(1);
    }

    const success = check(res, {
        'status is 200': (r) => r.status === 200,
        'response < 200ms (SLO)': (r) => r.timings.duration < SLO_THRESHOLD_MS,
        'response < 1s': (r) => r.timings.duration < 1000,
    });

    errorRate.add(!success);
}

export function teardown(data) {
    const elapsed = Math.round((Date.now() - data.startTime) / 1000);
    console.log('\n📊 ClarkNet Replay Complete');
    console.log('============================');
    console.log(`Total duration: ${elapsed}s`);
}

export function handleSummary(data) {
    const scenario = __ENV.SCENARIO || 'unknown';
    const run = __ENV.RUN_ID || '0';
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-');

    const summary = {
        scenario: scenario,
        run_id: parseInt(run),
        workload: 'clarknet_replay_fib34',
        timestamp: new Date().toISOString(),
        duration_sec: stages.length * 30,
        metrics: {
            p50_latency_ms: data.metrics.http_req_duration?.['p(50)'] || 0,
            p95_latency_ms: data.metrics.http_req_duration?.['p(95)'] || 0,
            p99_latency_ms: data.metrics.http_req_duration?.['p(99)'] || 0,
            error_rate: data.metrics.errors?.rate || 0,
            total_requests: data.metrics.http_reqs?.count || 0,
            actual_rps: data.metrics.http_reqs?.rate || 0,
            slo_violations: data.metrics.slo_violations?.count || 0,
        },
    };

    const outDir = __ENV.RESULTS_DIR || 'results/load-tests';

    return {
        [`${outDir}/clarknet_replay_${scenario}_run${run}_${timestamp}.json`]: JSON.stringify(data, null, 2),
        stdout: JSON.stringify(summary, null, 2),
    };
}
