apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-autoscaler
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-autoscaler
rules:
  # Permissions for general cluster resources
  - apiGroups: [""]
    resources:
      [
        "replicationcontrollers",
        "pods",
        "nodes",
        "persistentvolumeclaims",
        "events",
        "endpoints",
        "namespaces",
      ]
    verbs: ["get", "list", "watch", "create", "update", "patch"]

  # Permissions for eviction
  - apiGroups: [""]
    resources: ["pods/eviction"]
    verbs: ["create"]

  # Permissions for managing extensions and apps resources like ReplicaSets and Deployments
  - apiGroups: ["extensions", "apps"]
    resources: ["replicasets", "deployments", "statefulsets", "daemonsets"]
    verbs: ["list", "watch", "get"]

  # Permissions for batch jobs
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["list", "watch", "get"]

  # Permissions for PodDisruptionBudgets in the policy API group
  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["list", "watch", "get"]

  # Permissions for storage-related resources in the storage.k8s.io API group
  - apiGroups: ["storage.k8s.io"]
    resources:
      ["storageclasses", "csinodes", "csidrivers", "csistoragecapacities"]
    verbs: ["list", "watch", "get"]

  # Permissions for leases in coordination.k8s.io API group for leader election
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-autoscaler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-autoscaler
subjects:
  - kind: ServiceAccount
    name: cluster-autoscaler
    namespace: kube-system
