#!/usr/bin/env python3
"""
Generate k6 trace-driven replay artifacts from ClarkNet parquet data.

Pipeline (per thesis Section 3.2.4):
  Raw Parquet → 30s RPS Buckets → Scale → Trim → k6 Stages JSON + JS Script

Usage:
    cd controller && uv run python ../scripts/generate_trace_replay.py
    cd controller && uv run python ../scripts/generate_trace_replay.py --duration-min 5 --dry-run
"""

import argparse
import json
import sys
from pathlib import Path

import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = PROJECT_ROOT / "data" / "processed"
OUTPUT_DIR = PROJECT_ROOT / "data" / "trace-replay"
K6_SCRIPTS_DIR = PROJECT_ROOT / "infrastructure" / "load-tests"

# Selected window parameters (from exploration of clarknet_real_rps.parquet)
# idx=14470 → 1995-09-02 04:35:30 UTC, high variance window (cv=0.468)
DEFAULT_WINDOW_START_IDX = 14470
DEFAULT_SCALING_FACTOR = 33.0  # raw mean ~2.22 RPS → scaled mean ~73 RPS
DEFAULT_DURATION_MIN = 20  # 20 minutes = 40 × 30s buckets


def load_and_bucket(parquet_path: Path, bucket_sec: int = 30) -> pd.DataFrame:
    """Load parquet and resample to fixed-width RPS buckets."""
    df = pd.read_parquet(parquet_path)
    bucketed = df.resample(f"{bucket_sec}s").sum()
    bucketed.columns = ["total_requests"]
    bucketed["rps"] = bucketed["total_requests"] / bucket_sec
    return bucketed


def select_window(
    df: pd.DataFrame,
    start_idx: int,
    num_buckets: int,
) -> pd.DataFrame:
    """Select a contiguous window of num_buckets from the bucketed data."""
    if start_idx + num_buckets > len(df):
        raise ValueError(f"Window exceeds data: start={start_idx}, buckets={num_buckets}, data_len={len(df)}")
    return df.iloc[start_idx : start_idx + num_buckets].copy()


def apply_scaling(df: pd.DataFrame, scale_factor: float) -> pd.DataFrame:
    """Apply scaling factor g to RPS values."""
    df = df.copy()
    df["rps_scaled"] = (df["rps"] * scale_factor).round(0).astype(int)
    # Ensure at least 1 RPS (k6 needs positive targets)
    df["rps_scaled"] = df["rps_scaled"].clip(lower=1)
    return df


def generate_k6_stages(df: pd.DataFrame, bucket_sec: int = 30) -> list[dict]:
    """Convert scaled RPS buckets into k6 ramping-arrival-rate stages."""
    return [{"duration": f"{bucket_sec}s", "target": int(row["rps_scaled"])} for _, row in df.iterrows()]


def generate_k6_script(stages_json_path: str, output_path: Path) -> None:
    """Generate a k6 JS script that loads stages from JSON."""
    script = f"""/**
 * ClarkNet Trace-Driven Replay — k6 Load Test
 *
 * Generated by scripts/generate_trace_replay.py
 * Uses ramping-arrival-rate executor with 30-second stages derived from
 * the ClarkNet HTTP trace (Section 3.2.4 of thesis methodology).
 *
 * Usage:
 *   k6 run infrastructure/load-tests/clarknet_replay.js \\
 *     -e TARGET_URL=http://localhost:18082 \\
 *     -e SCENARIO=s4-hybrid-predictive
 */

import http from 'k6/http';
import {{ check }} from 'k6';
import {{ Rate, Trend, Counter }} from 'k6/metrics';

const errorRate = new Rate('errors');
const latencyTrend = new Trend('latency_ms');
const requestCounter = new Counter('total_requests');
const sloViolations = new Counter('slo_violations');

const SLO_THRESHOLD_MS = 200;

// Load stages from generated JSON
const stages = JSON.parse(open('{stages_json_path}'));

export const options = {{
    scenarios: {{
        clarknet_replay: {{
            executor: 'ramping-arrival-rate',
            startRate: stages[0].target,
            timeUnit: '1s',
            preAllocatedVUs: 200,
            maxVUs: 400,
            stages: stages,
        }},
    }},
    thresholds: {{
        'http_req_duration': ['p(95)<2000'],
        'http_req_duration': ['p(99)<5000'],
        'http_req_failed': ['rate<0.10'],
    }},
}};

const BASE_URL = __ENV.TARGET_URL || __ENV.BASE_URL || 'http://localhost:18082';
const ENDPOINT = __ENV.ENDPOINT || '/work?duration_ms=10';

export function setup() {{
    console.log('\\n🔬 ClarkNet Trace-Driven Replay');
    console.log('================================');
    console.log(`Stages: ${{stages.length}}`);
    console.log(`Duration: ${{stages.length * 30}}s (${{(stages.length * 30 / 60).toFixed(1)}} min)`);
    const rps_values = stages.map(s => s.target);
    console.log(`RPS range: [${{Math.min(...rps_values)}}, ${{Math.max(...rps_values)}}]`);
    console.log(`Target: ${{BASE_URL}}${{ENDPOINT}}`);
    console.log('');

    const warmup = http.get(`${{BASE_URL}}${{ENDPOINT}}`, {{
        headers: {{ 'Host': 'test-app.default.127.0.0.1.sslip.io' }},
    }});
    if (warmup.status !== 200) {{
        console.log(`⚠️ Warning: Warmup request returned ${{warmup.status}}`);
    }}

    return {{ startTime: Date.now() }};
}}

export default function () {{
    const res = http.get(`${{BASE_URL}}${{ENDPOINT}}`, {{
        headers: {{
            'Host': 'test-app.default.127.0.0.1.sslip.io',
        }},
    }});

    const duration = res.timings.duration;
    latencyTrend.add(duration);
    requestCounter.add(1);

    if (duration > SLO_THRESHOLD_MS) {{
        sloViolations.add(1);
    }}

    const success = check(res, {{
        'status is 200': (r) => r.status === 200,
        'response < 200ms (SLO)': (r) => r.timings.duration < SLO_THRESHOLD_MS,
        'response < 1s': (r) => r.timings.duration < 1000,
    }});

    errorRate.add(!success);
}}

export function teardown(data) {{
    const elapsed = Math.round((Date.now() - data.startTime) / 1000);
    console.log('\\n📊 ClarkNet Replay Complete');
    console.log('============================');
    console.log(`Total duration: ${{elapsed}}s`);
}}

export function handleSummary(data) {{
    const scenario = __ENV.SCENARIO || 'unknown';
    const run = __ENV.RUN_ID || '0';
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-');

    const summary = {{
        scenario: scenario,
        run_id: parseInt(run),
        workload: 'clarknet_replay',
        timestamp: new Date().toISOString(),
        duration_sec: stages.length * 30,
        metrics: {{
            p50_latency_ms: data.metrics.http_req_duration?.['p(50)'] || 0,
            p95_latency_ms: data.metrics.http_req_duration?.['p(95)'] || 0,
            p99_latency_ms: data.metrics.http_req_duration?.['p(99)'] || 0,
            error_rate: data.metrics.errors?.rate || 0,
            total_requests: data.metrics.http_reqs?.count || 0,
            actual_rps: data.metrics.http_reqs?.rate || 0,
            slo_violations: data.metrics.slo_violations?.count || 0,
        }},
    }};

    const outDir = __ENV.RESULTS_DIR || 'results/load-tests';

    return {{
        [`${{outDir}}/clarknet_replay_${{scenario}}_run${{run}}_${{timestamp}}.json`]: JSON.stringify(data, null, 2),
        stdout: JSON.stringify(summary, null, 2),
    }};
}}
"""
    output_path.write_text(script)


def main():
    parser = argparse.ArgumentParser(description="Generate k6 trace-driven replay from ClarkNet parquet")
    parser.add_argument(
        "--dataset",
        default="clarknet",
        choices=["clarknet", "calgary"],
        help="Dataset to use (default: clarknet)",
    )
    parser.add_argument(
        "--window-start",
        type=int,
        default=DEFAULT_WINDOW_START_IDX,
        help=f"Start index in 30s-bucketed data (default: {DEFAULT_WINDOW_START_IDX})",
    )
    parser.add_argument(
        "--scale-factor",
        type=float,
        default=DEFAULT_SCALING_FACTOR,
        help=f"RPS scaling factor g (default: {DEFAULT_SCALING_FACTOR})",
    )
    parser.add_argument(
        "--duration-min",
        type=int,
        default=DEFAULT_DURATION_MIN,
        help=f"Replay duration in minutes (default: {DEFAULT_DURATION_MIN})",
    )
    parser.add_argument(
        "--bucket-sec",
        type=int,
        default=30,
        help="Bucket width in seconds (default: 30)",
    )
    parser.add_argument(
        "--output-dir",
        type=str,
        default=None,
        help="Override output directory for trace artifacts",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print stages and stats without writing files",
    )

    args = parser.parse_args()

    # Resolve paths
    parquet_name = f"{args.dataset}_real_rps.parquet"
    parquet_path = DATA_DIR / parquet_name
    if not parquet_path.exists():
        print(f"❌ Parquet not found: {parquet_path}")
        return 1

    output_dir = Path(args.output_dir) if args.output_dir else OUTPUT_DIR
    num_buckets = (args.duration_min * 60) // args.bucket_sec

    # Pipeline
    print(f"📊 Loading {args.dataset} trace from {parquet_path.name}...")
    bucketed = load_and_bucket(parquet_path, args.bucket_sec)
    print(f"   {len(bucketed)} × {args.bucket_sec}s buckets total")

    print(f"📐 Selecting {num_buckets}-bucket window (start_idx={args.window_start})...")
    window = select_window(bucketed, args.window_start, num_buckets)
    print(f"   Time range: {window.index[0]} → {window.index[-1]}")
    print(f"   Raw RPS: mean={window['rps'].mean():.2f}, range=[{window['rps'].min():.1f}, {window['rps'].max():.1f}]")

    print(f"⚖️  Applying scale factor g={args.scale_factor}...")
    scaled = apply_scaling(window, args.scale_factor)
    print(
        f"   Scaled RPS: mean={scaled['rps_scaled'].mean():.0f}, "
        f"range=[{scaled['rps_scaled'].min()}, {scaled['rps_scaled'].max()}]"
    )

    stages = generate_k6_stages(scaled, args.bucket_sec)

    if args.dry_run:
        print(f"\n🔍 Dry run — {len(stages)} stages:")
        for i, s in enumerate(stages):
            print(f"  [{i:>2}] {s['target']:>4} RPS × {s['duration']}")
        print(f"\nTotal duration: {len(stages) * args.bucket_sec}s ({len(stages) * args.bucket_sec / 60:.1f} min)")
        return 0

    # Write artifacts
    output_dir.mkdir(parents=True, exist_ok=True)

    # 1. trace_30s_rps.csv
    csv_path = output_dir / f"{args.dataset}_trace_30s_rps.csv"
    scaled.to_csv(csv_path)
    print(f"✅ CSV: {csv_path}")

    # 2. k6_stages.json
    stages_path = output_dir / f"{args.dataset}_k6_stages.json"
    with open(stages_path, "w") as f:
        json.dump(stages, f, indent=2)
    print(f"✅ Stages JSON: {stages_path}")

    # 3. k6 JS script — uses path relative to the k6 script's directory
    stages_rel = str(Path("../../") / stages_path.relative_to(PROJECT_ROOT))
    js_path = K6_SCRIPTS_DIR / f"{args.dataset}_replay.js"
    generate_k6_script(stages_rel, js_path)
    print(f"✅ k6 script: {js_path}")

    # 4. Manifest
    manifest = {
        "dataset": args.dataset,
        "parquet": str(parquet_path.relative_to(PROJECT_ROOT)),
        "window_start_idx": args.window_start,
        "window_start_time": str(window.index[0]),
        "window_end_time": str(window.index[-1]),
        "bucket_sec": args.bucket_sec,
        "num_buckets": num_buckets,
        "duration_sec": num_buckets * args.bucket_sec,
        "scale_factor": args.scale_factor,
        "raw_rps_mean": round(float(window["rps"].mean()), 4),
        "raw_rps_min": round(float(window["rps"].min()), 4),
        "raw_rps_max": round(float(window["rps"].max()), 4),
        "scaled_rps_mean": int(scaled["rps_scaled"].mean()),
        "scaled_rps_min": int(scaled["rps_scaled"].min()),
        "scaled_rps_max": int(scaled["rps_scaled"].max()),
        "artifacts": {
            "csv": str(csv_path.relative_to(PROJECT_ROOT)),
            "stages_json": str(stages_path.relative_to(PROJECT_ROOT)),
            "k6_script": str(js_path.relative_to(PROJECT_ROOT)),
        },
    }
    manifest_path = output_dir / f"{args.dataset}_replay_manifest.json"
    with open(manifest_path, "w") as f:
        json.dump(manifest, f, indent=2)
    print(f"✅ Manifest: {manifest_path}")

    print("\n🎯 Pipeline complete. Run with:")
    print(f"   k6 run {js_path.relative_to(PROJECT_ROOT)} \\")
    print("     -e TARGET_URL=http://localhost:18082 \\")
    print("     -e SCENARIO=s4-hybrid-predictive")

    return 0


if __name__ == "__main__":
    sys.exit(main())
